---
title: "Assignment1-ggplot"
author: "Kukal"
date: "6/9/2022"
output: html_document
---

```{r libraries}
library(tidyverse)
library(readxl)
library(janitor)
```

```{r importing data}
data <- read_excel("../data/table-1.xls", skip = 3, n_max = 20)%>%
  clean_names()%>%
  data.frame()
years <- list(seq(1998,2017,1))
data1 <- replace(data, 1, years)
data1

summary(data)

```
1. Plot the violent crime rate versus time.
```{r plot-1}

ggplot(data1, aes(x = year, y =violent_crime_rate))+
  geom_line(color = "red", size = 2)+
  geom_point(size = 4)+
  ylim(300,600)+
  ggtitle("Time vs Violent Crime Rate")+
  theme_linedraw()+
  theme(plot.title = element_text(size = 20, face = "bold"))+
  ylab("Violent Crime Rate")+
  xlab("Year")
  


```


2.Make a plot with separate lines for the rate of each type of violent crime and
also the total rate of violent crimes.
```{r plot-2}

ggplot(data1, aes(x = year))+
  geom_line(aes(y= murder_and_nonnegligent_manslaughter), color = "red", size = 1)+
  geom_point(aes(y= murder_and_nonnegligent_manslaughter))+
  geom_line(aes(y= rape_legacy_definition_4), color = "blue", size = 1)+
  geom_point(aes(y= rape_legacy_definition_4))+
  geom_line(aes(y= aggravated_assault), color = "green", size = 1)+
  geom_point(aes(y= aggravated_assault))+
  geom_line(aes(y= robbery), color = "brown", size = 1)+
  geom_point(aes(y= robbery))+
  geom_line(aes(y= violent_crime_rate), color = "black", size = 1)+
  geom_point(aes(y= violent_crime_rate), color = "sea green")+
  ggtitle("Various Violent Crimes")+
  theme_linedraw()+
  theme(plot.title = element_text(size = 20, face = "bold"))+
  xlab("Year")+
  ylab("Voilent Crimes")
  

```



3.Plot the property crime rate versus time.
```{r plot-3}

ggplot(data1, aes(x = year, y =property_crime/10000))+
  geom_line(color = "red", size = 2)+
  geom_point(size = 4)+
  ggtitle("Property Crime")+
  theme_linedraw()+
  theme(plot.title = element_text(size = 20, face = "bold"))+
  ylab("Property Crime/10000")+
  xlab("Year")



```



4. Make a plot with separate lines for the rate of each type of property crime and
also the total rate of property crimes.
```{r plot-4}




```

